name: Lint Argo Workflows
description: Lint Argo Workflows
author: GitHub Actions

inputs:
  manifests:
    description: Path to raw WorkflowTemplates manifests
    required: false
  charts:
    description: Path to helm-based WorkflowTemplates
    required: false

runs:
  using: docker
  image: Dockerfile
  env:
    MANIFEST: ${{ inputs.manifests }}
    CHARTS: ${{ inputs.charts }}
