apiVersion: v1
kind: Config
preferences: {}
current-context: user@cluster
clusters:
  - name: cluster
    cluster:
      server: https://url.co.uk
contexts:
  - name: user@cluster
    context:
      cluster: cluster
      user: user
users:
  - name: user
    user:
      token: dummy-token
